### ISSUE TITLE
Assets license

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [BlindMindStudios/StarRuler2-Source#2]
Can you please release also the assets with a free license? For example CC-BY-SA?

**Comment by abenson** [comment]
From COPYING

~~~
All contained art assets, images and 3d models are licensed under the Creative Commons CC-BY-NC 2.0 license as found at https://creativecommons.org/licenses/by-nc/2.0/legalcode.
~~~

**Comment by DaloLorn** [comment]
CC-BY-SA would allow commercial use, which is not permitted under CC-BY-NC. I suspect that the devs chose the more restrictive version on purpose; there are a number of reasons why they wouldn't want to let people make money off of their assets. (Even more so when you consider the fact that, if I'm reading the licenses correctly, it is _technically_ legal for someone to bundle the entire contents of the repository and distribute copies of SR2 that are inferior to the original only in that they don't come with any music.)*

* - This interpretation of the license would also allow a third party to make a commercial SR2 clone by replacing *every last bit* of art in the repository with their own graphics. Personally, I can't imagine why anyone would want to go to all that trouble to merely reskin the game, but who knows?

**Comment by subchannel13** [comment]
@DaloLorn Don't underestimate asset flippers. They'd take code from here, assets from somewhere else and flood Steam with million clones.

**Comment by DaloLorn** [comment]
Point taken. Still, blocking the assets will at least prevent people from literally republishing the game as their own.

**Comment by emorrp1** [comment]
This is also a concern for Debian packaging - [The Debian Free Software Guidelines (DFSG)](https://www.debian.org/social_contract#guidelines) accept NC as open source, but not free software, so would be labelled as "non-free" in Debian. FYI, Lugaru HD also [went through this](https://gitlab.com/osslugaru/lugaru/commit/51203b531b2054a8a7c40356e2108a5ec7b9f366?view=parallel) before being moved to Debian "main".

> No Discrimination Against Fields of Endeavor
> 
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

I'm *really* not knocking BlindMindStudios for their awesome contribution, but it would be nice if they could clarify the reasons for choosing CC-BY-NC for the assets? If it is due to asset flippers, perhaps you'd consider re-licensing in e.g. 5 years to CC-BY-SA?

**Comment by JonMicheelsen** [comment]
I made the choice of CC-BY-NC for the assets, since I made a majority of the 3D models and their texture assets, unpaid, for the learning experience. I don't want to see them pop up in some commercial context without being able to say no, or yield the ability to clean them up in another format and put them on an asset store.

**Comment by ThyReaper** [comment]
The asset license won't be changing any time soon.

**Comment by Wuzzy2** [comment]
Hey, @ThyReaper, I am not here to belittle any of your work, nor to force you to do anything.

But I am too asking you to please reconsider your choice of license.

The reason is that the NC clause is commonly misunderstood.
The definition of “NonCommercial” in the license is quite vaguely formulated and is much broader than you might think and has lots of surprising negative effects which you might not have intended.
Most importantly, NC means that some benefitial uses of your work are ruled out or become difficult/impractial:

- Let's Play videos on YouTube, but with video ads (some let's players actually depend on this money)
- Putting the game on a website which has even the *slightest* hint of being commercial. One tiny ad would be enough
- Putting the game on most GNU/Linux distributions
- Posting high resolution screenshots on Wikipedia
- Remixing and combination of the artwork with free artwork

In other words, the people that NC is hurting the most are people like you and me, and not \<INSERT EVIL BIG MEGACORPORATION HERE\>. Those people are also rarely having the resources nor desire to do an asset flip.

If it really was your goal to forbid all those uses above, then yes, NC is definitely the right choice. However, if this is not your intention, then CC BY-NC was a wrong choice which goes against your intentions. In that case, you should reconsider *in your own interest*.

I can totally understand that you want to prevent exploitation. For this, a share-alike license like CC BY-SA is protecting your work from exploitation quite well while still being considered open source. Win-win. :-) While it does allow commercial use, it does not allow people to monopolize your work or claim it as their own or slap their own terms and conditions on it.

Note I have no personal interest in turning this game into a profit. I am posting this more for philosophical reasons. I also like to see this game to be adopted in GNU/Linux distributions. Having a free culture license would definitely make this a ton easier. :-)

If you have a bit more time to read, on <https://freedomdefined.org/Licenses/NC> there's a great explanation of reasons why the NC is considered problematic by some; maybe it helps to see where I'm coming from.

Have a nice day!

**Comment by DaloLorn** [comment]
@Wuzzy2 I think you were trying to ping @JonMicheelsen there...? Reaper was the one explaining things in your original issue.

**Comment by GGLucas** [comment]
I feel I should add a clarification here, as most of the examples brought up by Wuzzy2 here are simply not true.

> Let's Play videos on YouTube, but with video ads (some let's players actually depend on this money)

These are widely taken to be under 'Fair Use' doctrine, and do not need a license at all to make money. Granted there is still a bit of a grey area here, anyone who is worried about this is free to contact us directly as well, although it should not be needed.

> Putting the game on a website which has even the slightest hint of being commercial. One tiny ad would be enough

Completely false. CC-BY-NC only restricts uses that are **primarily** intended for commercial use, ads on a distributing website would not be an issue.

> Putting the game on most GNU/Linux distributions

The license in no way prevents distributions from packaging the game. Some distributions have **chosen** to disallow non-commercial licenses in their main repositories, but there is no reason they should need to. Additionally, pretty much every GNU/Linux distribution has a repository that does allow these.

> Posting high resolution screenshots on Wikipedia

Again this is only by Wikipedia's choice. There's nothing in the license that would stop wikipedia from hosting the assets wholesale even. Screenshots are generally considered Fair Use as well, wikipedia just decided to take the safer route here.

> Remixing and combination of the artwork with free artwork

False again. It only prevents combination with Share-Alike copyleft licenses, which on a personal tangent I feel should be discouraged in general. There is nothing in the license preventing you from mixing it with other CC-BY, CC-BY-NC, or public domain artwork.

**Comment by Wuzzy2** [comment]
I am posting this as response to the previous post. I think you are making this matter a little bit too easy for you.

> These are widely taken to be under 'Fair Use' doctrine, and do not need a license at all to make money. Granted there is still a bit of a grey area here, anyone who is worried about this is free to contact us directly as well, although it should not be needed.

Well, if you need explicit permission to clarify, then that defeats the point of a license. It's just the same as with a full copyright then.

The legality of let's plays is still a gray area, which sucks. If a LPer would be legally challenged, we don't know for sure what will come out of it. Whether the fair use doctrine actually will be a viable defense, we don't really know yet. Plus, not all countries even have Fair Use. Rightsholders so far have merely been tolerating let's plays so far.

Besides, historically, courts have decided in favour of copyright holder rather than the (supposed) violator.

> CC-BY-NC only restricts uses that are primarily intended for commercial use, ads on a distributing website would not be an issue.

This is only true in theory. In practice, the definition of “NonCommercial” is quite vague. You may use the work for “for NonCommercial purposes only”. And the definition of “NonCommercial” is:

> NonCommercial means not primarily intended for or directed towards commercial advantage or monetary compensation.

These weasel words should be red flags. “not primarily intended or directed towards” … is open to interpretation. “commercial advantage” is even more vague. It should be without saying, if you throw this license at a court, funny things will happen. Also, how can you be so sure that “using ads on a website” is not a problem? It sure is commercial. Whether this is in violation is a great topic of debate. Which is bad if you need clarity.
For example, the Deutschlandfunk (German public radio, 100% taxfunded) has been legally sued for using NC-ed content. http://www.ifross.org/artikel/lg-k-ln-beschr-nkt-cc-nc-rein-private-nutzungen

With this legal uncertainty, it is a totally rational and understandable decision to avoid any NC-ed material at all costs, even if they believe they are NonCommercial. I find it a bit strange to move the blame on (some) GNU/Linux distributions and Wikipedia, as if it is somehow their fault that authors have chosen that license.

> There's nothing in the license that would stop wikipedia from hosting the assets wholesale even.

At least for the German Wikipedia this would be a dangerous move to open the flood gates for NC-ed content, given the Deutschlandfunk case. In fact, it would be suicide.

Wikimedia also collects tons of money via donations. This *might* be a problem (I don't know). But given the vague wording (e.g. “monetary compensation”), everything is possible.

> > Remixing and combination of the artwork with free artwork

> False again. It only prevents combination with Share-Alike copyleft licenses,

Well, that's what I meant. I did not say it's a problem with *all* free content. Anyway, incompability with share-alike is bad enough. It's still an avoidable license incompability which you just downplay as if it would not be a big deal.

**Comment by jdoe0** [comment]
@JonMicheelsen 

> I don't want to see them pop up in some commercial context without being able to say no, or yield the ability to clean them up in another format and put them on an asset store.

CC-BY-SA does not prevent you from putting your assets in a store. You, as the copyright holder, are not bound by restrictions in the license; you are free to re-publish your own assets (not including changes made by others) in any license you want.

**Comment by DaloLorn** [comment]
> > I don't want to see them pop up in some commercial context without being able to say no, or yield the ability to clean them up in another format and put them on an asset store.
> 
> CC-BY-SA does not prevent you from putting your assets in a store. You, as the copyright holder, are not bound by restrictions in the license; you are free to re-publish your own assets (not including changes made by others) in any license you want.

While technically true, it is also plausible that someone might do it before him. Also, you completely failed to address his first concern, which was not having any say in whether someone _does_ use his assets commercially.

**Comment by jdoe0** [comment]
>While technically true, it is also plausible that someone might do it before him.

I'm not familiar with how asset stores work, but if the store requires the assets to be published under a particular license, then he will be the only person who can do it.

>Also, you completely failed to address his first concern, which was not having any say in whether someone does use his assets commercially.

It's true that he won't be able to stop people from using his assets in commercial contexts if he removes the non-commercial restriction; I don't really have anything else to say about this.

**Comment by rfht** [comment]
@jdoe0 @Wuzzy2 thanks for doing everyone who is interested in open source games *beyond the license nit-picking* for actively discouraging developers to do this ever again. BlindMindStudios is one of the few really great examples of where this was done with a game that has high production value and was still recently on sale. The assets are available at all (unlike Quake, Doom, etc), and the license situation is decent - compare it for example to the mess with fs2open! If there was leeway for changing the asset license to CC-BY-SA, this would be clear by now. Not only do I not see the point in the discussion about the assets, I also think that this type of discussion is damaging for the open source gaming community at this point.

**Comment by jdoe0** [comment]
@rfht 
I'm not criticizing the developers for using a nonfree license for the assets; I'm just pointing out factual inaccuracies. I do appreciate their decision to release the source code and assets even with the current licenses.

**Comment by Wuzzy2** [comment]
@rfht:
I am not discouraging anyone from releasing games as open source / free software, quite the contrary. *Of course* it's great to see developers releasing high-quality work as free software. Even if it is only a partial release like the engine code (for now). I just thought it would have been *even better* if the *entire* game were under free-as-in-freedom licenses. That was my request, and I have explained my reasons before.

I repeat: This was a *request*, not a *demand*. Note I also have not insulted anyone here.

If you think my reasons are not justified, fine, but please don't tell me I am “damaging” or “harmful” for stating my opinion and stating facts.

I think it is unfair to reduce this discussion to “license nit-picking”. That's not the point. My point is always freedom. The choice of the license does have a real world impact, it's not a minor detail. The difference between e.g. CC BY-NC and CC-BY-SA is significant. I wanted to make sure the choice of NC was a) really intentional and b) the real world implications were understood. Because the impact of this license is often misunderstood. I encourage you to read up on criticism and several *practical problems* with the idea of NonCommercial: https://freedomdefined.org/Licenses/NC

I can understand why the topic of freedom is uncomfortable to some people, but that doesn't mean I have to keep my mouth shut forever. I'm not an evil person.

---

@JonMicheelsen:
Now that there has been some discussion about the license, have you changed your mind? I mean, would you please choose a free culture license for the media? Such as CC BY-SA or CC BY?

If the answer is “yes”, then I and the rest of the free software world will be grateful forever. :-)
If the answer is still “no” or refuse to answer, I will no longer bother you with this topic, I have said everything I had to say. No pressure.

**Comment by subchannel13** [comment]
@Wuzzy2 To someone unversed in the great rabbit hole of open source licenses your posts before the last one did come across as attacking devs over license nit-picking. That's not about you that's about people who have only surface or no knowledge of licenses. For them it sounds like you are accusing devs for not knowing enough details in this particular domain.

But thank you making me learn more about CC licenses.

**Comment by DaloLorn** [comment]
I think the issue isn't one of content, but one of tone. The discussion seemed more hostile than it should have been, so I can see why rfht would perceive it as possibly discouraging towards future open-sourcing.
